spring:
  data:
    mongodb:
      uri: mongodb+srv://varun:vmv2021@cluster0.uhwsn.mongodb.net/team_crew_db?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal